# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
  redis:
    database: 0 # 连接哪个数据库
#    cluster: #集群连接
#      nodes: 192.168.137.135:7000,192.168.137.135:7001,192.168.137.135:7002,192.168.137.136:7003,192.168.137.136:7004,192.168.137.136:7005
#      max-redirects: 3 # 获取失败 最大重定向次数
    sentinel:
      master: mymaster
      nodes: 192.168.137.136:7003,192.168.137.136:7004,192.168.137.136:7005
    commandTimeout: 5000  #设置命令的执行时间，如果超过这个时间，则报错;
    max-redirects: 3
    ssl: false #启用SSL终端识别
    password:
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
server:
  port: 8899

#spring.redis.host: localhost
#spring.redis.port: 6379
#spring.redis.database: 1
#spring.redis.password: 123456

##初始化时建立物理连接的个数
#spring.datasource.druid.initial-size: 3
##最小连接池数量
#spring.datasource.druid.min-idle: 3
##最大连接池数量
#spring.datasource.druid.max-active: 10
##获取连接时最大等待时间
#spring.datasource.druid.max-wait: 60000
##配置监控页面访问登录名称
#spring.datasource.druid.stat-view-servlet.login-username: admin
##配置监控页面访问密码
#spring.datasource.druid.stat-view-servlet.login-password: admin
##是否开启慢sql查询监控
#spring.datasource.druid.filter.stat.log-slow-sql: true
##SQL合并配置
#spring.datasource.druid.filter.stat.merge-sql: true
##慢SQL执行时间
#spring.datasource.druid.filter.stat.slow-sql-millis: 5000

# nacos
spring.cloud.nacos.discovery.server-addr: localhost:8848
spring.cloud.nacos.discovery.namespace: 4e0eaa6c-bb62-4829-a0ed-1734bdf788bf

center:
  wxp:
    log:
      enabled: true
      enabled-global-print: true
      position: ALL
#证书信息
#server.ssl.key-store: classpath:cainiao.keystore
#server.ssl.key-store-password: 123456
#server.ssl.key-password: 123456
##查询账号密码sql，必须包含密码字段
#cas.authn.jdbc.query[0].sql: select * from sys_user where username = ?
##指定上面的sql查询字段名（必须）
#cas.authn.jdbc.query[0].fieldPassword: password
##指定过期字段，1为过期，若过期需要修改密码
#cas.authn.jdbc.query[0].fieldExpired: expired
##为不可用字段段，1为不可用，
#cas.authn.jdbc.query[0].fieldDisabled: disabled
##数据库方言hibernate的知识
#cas.authn.jdbc.query[0].dialect: org.hibernate.dialect.MySQLDialect
##数据库驱动
#cas.authn.jdbc.query[0].driverClass: com.mysql.jdbc.Driver
##数据库连接
#cas.authn.jdbc.query[0].url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
##数据库用户名
#cas.authn.jdbc.query[0].user: root
##数据库密码
#cas.authn.jdbc.query[0].password: 123456
##默认加密策略，通过encodingAlgorithm来指定算法，默认NONE不加密
#cas.authn.jdbc.query[0].passwordEncoder.type: DEFAULT
#cas.authn.jdbc.query[0].passwordEncoder.characterEncoding: UTF-8
#cas.authn.jdbc.query[0].passwordEncoder.encodingAlgorithm: MD5
