# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8888

spring.redis.host: localhost
spring.redis.port: 6379
spring.redis.database: 1
spring.redis.password: 123456