# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8888

spring.redis.host: localhost
spring.redis.port: 6379
spring.redis.database: 1
spring.redis.password: 123456

# nacos
spring.cloud.nacos.discovery.server-addr: 10.10.11.107:25100
spring.cloud.nacos.discovery.namespace: 4e167baf-178c-4aa7-8557-c82b097c029c

center:
  wxp:
    log:
      enabled: true
      enabled-global-print: true
      position: ALL
