# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8888

spring.redis.host: localhost
spring.redis.port: 6379
spring.redis.database: 1
spring.redis.password: 123456

#初始化时建立物理连接的个数
spring.datasource.druid.initial-size: 3
#最小连接池数量
spring.datasource.druid.min-idle: 3
#最大连接池数量
spring.datasource.druid.max-active: 10
#获取连接时最大等待时间
spring.datasource.druid.max-wait: 60000
#配置监控页面访问登录名称
spring.datasource.druid.stat-view-servlet.login-username: admin
#配置监控页面访问密码
spring.datasource.druid.stat-view-servlet.login-password: admin
#是否开启慢sql查询监控
spring.datasource.druid.filter.stat.log-slow-sql: true
#SQL合并配置
spring.datasource.druid.filter.stat.merge-sql: true
#慢SQL执行时间
spring.datasource.druid.filter.stat.slow-sql-millis: 5000

# nacos
spring.cloud.nacos.discovery.server-addr: 10.10.11.107:25100
spring.cloud.nacos.discovery.namespace: 4e167baf-178c-4aa7-8557-c82b097c029c

center:
  wxp:
    log:
      enabled: true
      enabled-global-print: true
      position: ALL
