server:
  port: 8089
spring:
  application:
    name: mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: ${REDIS_HOST:localhost}
  port:  ${REDIS_PORT:6379}
  password: 123456
  timeout: 2000
  # 服务或应用名
  sysName: ace-admin
  enable: true
  database: 0